ModuleConfiguration:
    as_extra_charger_info: False
    msic_bcu_current_path: ""
    battery_interrupts: []
    batt_capacity: ""
    bcu_interrput: []
    #since common ics : ""
    thermal_orig_file: ""
    thermal_file: ""
    charger_enable_file_path: ""
    # VAR RELATED TO CHARGER
    possible_charger_name: []
    mode_mapping:
        "on": 0
        "off": 0
        "low": 0
        "medium": 0
        "high": 0
    mode_mapping_cooling_device:
        "on": 0
        "off": 0
        "low": 0
        "medium": 0
        "high": 0
