ModuleConfiguration:
   chrome_app: "Chrome_M44_Stable_44.0.2403.133_x86.apk"
   gl_benchmark_212: "GLBenchmark_2.1.2_EF23DA_Android_Binary_Package.apk"
   gl_benchmark_251: "GLBenchmark_2_5_1_b306a5_Android_Corporate_Package.apk"
   gl_benchmark_270: "GLBenchmark_2_7_0_Release_a68901_Android_Corporate_Package.apk"
   stepcounter_app: "StepCounterTest.apk"
   3dmark_app: "3dmarkandroid-v1.3.1375.apk"
   3dmark_dlc: "is-android-data-42_0_0.dlc"
   angrybirds_app: "angrybirds4p2p1.apk"
   angrybirds_events: "AngryBirds-events.tar.gz"
   angrybirds_activity: "com.rovio.angrybirds/com.rovio.fusion.App"
   network_simulator_files:
      IDLE: "PNP_NETWORK_SIM_CONFIG_CHT.xml"
      STREAMING: "PNP_NETWORK_SIM_CONFIG_CHT.xml"
      BROWSING: "PNP_NETWORK_SIM_CONFIG_CHT.xml"
      ACTIVE_IDLE: "PNP_NETWORK_SIM_CONFIG_CHT.xml"
      VOICE_CALL: "PNP_NETWORK_SIM_CONFIG_CHT.xml"
   umic_config_file: "UMIC_2MP.xml"
   video_playback_h264_720p_30fps: ToS_720p_29.97fps_H264_4000kbps_8bits_noHDR_v1511090000.mp4
   video_playback_h264_720p_30fps_barcoded: ToS_720p_29.97fps_H264_4000kbps_8bits_noHDR_barcoded-v1511090000.mp4
   video_playback_h264_1080p_30fps: ToS_1080p_29.97fps_H264_12000kbps_8bits_noHDR_v1511090000.mp4
   video_playback_h264_1080p_30fps_barcoded: ToS_1080p_29.97fps_H264_12000kbps_8bits_noHDR_barcoded-v1511090000.mp4
   video_playback_h265_1080p_30fps: ToS_1080p_29.97fps_H265_8000kbps_8bits_noHDR_v1511090000.mp4
   video_playback_h264_1080p_60fps_barcoded: ToS_1080p_59.94fps_H264_25000kbps_8bits_noHDR_barcoded-v1511090000.mp4
   video_playback_h264_2160p_30fps: ToS_2160p_29.97fps_HEVC_35000kbps_8bits_noHDR_v1511090000.mp4
   video_playback_h264_2160p_30fps_barcoded: ToS_2160p_29.97fps_HEVC_35000kbps_8bits_noHDR_barcoded-v1511090000.mp4
   video_playback_h265_2160p_30fps: ToS_2160p_29.97fps_H265_35000kbps_8bits_noHDR_v1511090000.mp4
   video_playback_h264_2160p_60fps_barcoded: ToS_2160p_59.94fps_H264_35000kbps_8bits_noHDR_barcoded-v1511090000.mp4
   video_record_2160_config_file: "VR2160p30SDV16MP.xml"
   video_record_1080_config_file: "VR1080p30SDV3p7MP.xml"
   video_record_720_config_file: "VR720p30fps.xml"
   sipnpperf_chrome_app: Chrome_M44_Stable_44.0.2403.133_x86.apk
   sipnpperf_0xbench_app: 0xbench_M_v1.0.apk
   sipnpperf_andebench_app: AndeBench.apk
   sipnpperf_androbench_app: AndroBench-3.4.apk
   sipnpperf_antutu_app: AnTuTu-5.6.apk
   sipnpperf_basemark_app: BasemarkES2v1_2.apk
   sipnpperf_basemark_rightware_2v1_2_pkg: Basemark_rightware2v1_2
   sipnpperf_benchmark_pi_app: BenchMarkPi.apk
   sipnpperf_caffeinemark_app: com.android.cm3-1.apk
   sipnpperf_cfbench_app: Eu.chainfire.cfbench-1.apk
   sipnpperf_compubenchrs_app: compubenchrs2p0p1-corporate5f77bdc8-memleakfixed.apk
   sipnpperf_coremark_app: coremark_1T_ICC14_BETA_xatom_sse42.exe
   sipnpperf_dhrystone_app: dhrystone_2
   sipnpperf_disableverity_cmd: "adb devices"
   sipnpperf_display_turnon_trace: "Display DrmDisplay Unblank complete"
   sipnpperf_droidbot_agent: Droidbot-agent.apk
   sipnpperf_droidbot_corelib: droidbot-corelib.jar
   sipnpperf_droidbot_pnptests: droidbot-pnptests.jar
   sipnpperf_epiccitadel_app: com.epicgames.EpicCitadel.apk
   sipnpperf_epiccitadel_obb: main.902107.com.epicgames.EpicCitadel.obb
   sipnpperf_fishtank_pkg: Fishtank_RAF_200Fish
   sipnpperf_flatland_app: FLATLAND_M
   sipnpperf_flatland_height: 800
   sipnpperf_geekbench_app: Geekbench3.3.1-Android.apk
   sipnpperf_gfxbench_app: GFXBench_3_1_1_Corporate_Android_Binary_10_12_2015.apk
   sipnpperf_gl_benchmark_270: GLBenchmark_2_7_0_Release_a68901_Android_Corporate_Package.apk
   sipnpperf_icyrocks_app: GameWorkload-no-debug.apk
   sipnpperf_icyrocks_launcher: GameWorkloadLauncher-no-debug.apk
   sipnpperf_ispec_app: spec_icc11_repackaged.tar.gz
   sipnpperf_jio_app: JIO_V1.7.2.apk
   sipnpperf_jio_conf: 1GB_system_1T_test_configuration.xml
   sipnpperf_kraken_pkg: kraken-1.1
   sipnpperf_mobilexprt_app: MobileXPRTInstaller_64b_WW17.apk
   sipnpperf_octane_pkg: octane_v1
   sipnpperf_octane_path: /octane/index.html
   sipnpperf_quadrant_app: quadrant.ui.professional-2.1.1.apk
   sipnpperf_rl_bench_app: RL_SQLite-1.3.apk
   sipnpperf_smartbench_app: smartbench.2012-1.apk
   sipnpperf_stream_app: icc_tuned2
   sipnpperf_sunspider_pkg: sunspider-1.0.2
   sipnpperf_vellamo_app: Vellamo-3.2.apk
   sipnpperf_vellamo_assets: Vellamo-3.2-app_assets3.tgz
   sipnpperf_browsingbench_url: http://10.1.1.179
   sipnpperf_browsermark_url: http://10.1.1.217:81/tests/2.1
   sipnpperf_fishtank_url: http://10.1.1.199/Fishtank/test.php
   sipnpperf_kraken_url: http://10.1.1.199/auto_kraken/hosted/kraken-1.1/driver.html
   sipnpperf_octane_url: http://10.1.1.199/auto_octane/index.html
   sipnpperf_sunspider_url: http://10.1.1.199/auto_sunspider/sunspider-1.0.2/sunspider-1.0.2/driver.html
   sipnpperf_webxprt_url: http://10.1.1.216/v1dot01/login.php
   sipnpperf_droidbot_v2_apk: droidbot-v2-agent.apk
   mmc0readahead: /sys/devices/pci0000:00/80860F14:00/mmc_host/mmc0/mmc0:0001/block/mmcblk0/queue/read_ahead_kb
   readahead_value: 512
   dpi_value: 213
   governor: acpi-cpufreq
   mid_ram: True
