ModuleConfiguration:
    as_extra_charger_info: False
    msic_bcu_current_path: "/sys/devices/pci0000:00/0000:00:18.7/i2c-7/7-006e/crystal_cove_bcu/msic_voltage/"
    battery_interrupts: ["intel_mdf_battery", "max170xx_battery", "ulpmc-battery"]
    batt_capacity: "/sys/class/*ower_supply/*battery/capacity"
    bcu_interrput: ["msic_vdd", "bcove_bcu", "crystal_cove_bcu"]
    possible_charger_name: ["charger", "smb", "b*_charger", "bq"]
    thermal_orig_file: "/etc/thermal_sensor_config.orig"
    thermal_file: "/etc/thermal_sensor_config.xml"
    charger_enable_file_path: "/sys/class/power_supply/bq24192_charger/device/charge_current_limit"
    msic_shell_folder: "/logs/"
    mode_mapping:
        "on": 4
        "off": 0
        "low": 1
        "medium": 2
        "high": 3
    mode_mapping_cooling_device:
        "on": 0
        "off": 3
        "low": 2
        "medium": 1
        "high": 0
