ADB_CMD_PREFIX = "adb -s %s "
ADB_SHELL_CMD_PREFIX = "adb -s %s shell "
ADB_PULL_CMD = "adb -s %s pull "
ADB_PUSH_CMD = "adb -s %s push "
ADB_INPUT_KEYEVENT_CMD = " input keyevent "
ADB_INPUT_TEXT_CMD = " input text "
ADB_INPUT_TAP_CMD = "input tap "
ADB_INPUT_LONG_TAP_CMD = "input touchscreen swipe "

DUT_SDCARD_DIR = "/sdcard/"
DEL_CMD = "rm -rf "
CP_CMD = "cp "
MKDIRS_CMD = "mkdir -p "
CREATE_FILE_CMD = "touch "
PRINT_INTO_FILE_CMD = "printf "
CAT_CMD = "cat "
LS_CMD = "ls -al "
RENAME_CMD = "mv "
COPY_R_CMD = "cp -r "

REDIRECT_SYMBOL = ">"
TICK = "'"
QUOTE = '"'
SPACE = " "
