# Android 5.0 Lollipop string id's for chrome views
ANDROID_VERSION = "N"

### Chrome Elements
CHROME_SHORTCUT_NAME = "Chrome"
CHROME_OPTIONS_DESC = "More options"
CHROME_OPTION_RESID = "com.android.chrome:id/menu_button"
CHROME_EMPTY_OPTION_RESID = "com.android.chrome:id/empty_menu_button"
CHROME_OPTION_DOCUMENT_RESID = "com.android.chrome:id/document_menu_button"
CHROME_NEW_TAB_OPTION_NAME = "New tab"
CHROME_NEW_INCOGNITO_TAB_OPTION_NAME = "New incognito tab"
CHROME_ADDRESS_BAR_RESID = "com.android.chrome:id/url_bar"
CHROME_ADDRESS_BAR_TEXT = "Search or type URL"
CHROME_TAB_SWITCHER_RESID = "com.android.chrome:id/tab_switcher_button"
CHROME_CLOSE_TABS_OPTION_NAME = "Close all tabs"
CHROME_OPEN_LINK_IN_NEW_TAB = "Open in new tab"
CHROME_WEBKIT_CLASS = "android.webkit.WebView"
CHROME_PACKAGE_NAME = "com.android.chrome"
CHROME_FRAME_LAYOUT_CLASS = "android.widget.FrameLayout"
CHROME_PRINT_OPTION = "Print"
PRINT_SPOOLER_PACKAGE_NAME = "com.android.printspooler"
CHROME_BACK_BUTTON_RESID = "com.android.chrome:id/back_button"
CHROME_FORWARD_BUTTON_RESID = "com.android.chrome:id/forward_button"
CHROME_REFRESH_BUTTON_RESID = "com.android.chrome:id/refresh_button"
CHROME_CONTROL_CONTAINER_RESID = "com.android.chrome:id/control_container"
CHROME_ACCEPT_TERMS_RESID = "com.android.chrome:id/terms_accept"
CHROME_NEGATIVE_BUTTON_RESID = "com.android.chrome:id/negative_button"
CHROME_WEB_VIEW_DESC = "Web View"
CHROME_FIND_IN_PAGE_MENU_OPTION = "Find in page"
CHROME_FIND_QUERY_RESID = "com.android.chrome:id/find_query"
CHROME_FIND_STATUS_RESID = "com.android.chrome:id/find_status"
CHROME_HELP_TXT = "Help"
CHROME_FEEDBACK_TXT = "Feedback"
CHROME_HELP_AND_FEEDBACK_MENU_OPTION = "Help & feedback"
CHROME_MOST_VISITED_TITLE_RESID = "com.android.chrome:id/most_visited_title"
CHROME_BOOKMARK_BUTTON_RESID = "com.android.chrome:id/bookmark_button"
CHROME_BOOKMARK_BUTTON_RESID_SOFIA = "com.android.chrome:id/button_two"
CHROME_BOOKMARKS_OPTION_MENU_TXT = "Bookmarks"
CHROME_POPUPS_SWITCH_RESID = "com.android.chrome:id/switch_widget"
CHROME_REQ_DESKTOP_SITE_TXT = "Request desktop site"
CHROME_BOOKMARK_TITLE_INPUT_RESIDS = ["com.android.chrome:id/title_text", "com.android.chrome:id/bookmark_title_input"]
CHROME_BOOKMARK_URL_INPUT_RESIDS = ["com.android.chrome:id/url_text", "com.android.chrome:id/bookmark_url_input"]
CHROME_BOOKMARK_FOLDER_SELECT_RESIDS = ["com.android.chrome:id/folder_text", "com.android.chrome:id/bookmark_folder_select"]
CHROME_BOOKMARK_FOLDER_EDIT_RESIDS = ["com.android.chrome:id/folder_title"]
CHROME_ADD_BOOKMARK_SAVE_TXT = "Save"
CHROME_ADD_BOOKMARK_SAVE_DESC = "Save"
CHROME_ADD_BOOKMARK_CANCEL_TXT = "Cancel"
CHROME_CHOOSE_FOLDER_NEW_FOLDER_RESID = "com.android.chrome:id/new_folder_btn"
CHROME_MOBILE_BOOKMARKS_FOLDER_DESC = "Mobile bookmarks folder"
CHROME_TOOLBAR_CONTAINER_RESID = "com.android.chrome:id/toolbar_container"
CHROME_TOOLBAR_RESID = "com.android.chrome:id/toolbar"
CHROME_TEXT_SCALING_TXT = "Text scaling"
CHROME_TEXT_SCALING_SEEKBAR_RESID = "com.android.chrome:id/seekbar"
CHROME_TEXT_SCALING_SEEKBAR_AMOUUNT_RESID = "com.android.chrome:id/seekbar_amount"
CHROME_CLEAR_BROWSING_DATA_BUTTON_TXT = "Clear browsing data"
CHROME_CLEAR_TXT = "CLEAR DATA"
CHROME_NEW_FOLDER_BUTTON_TXT = "New folder"
CHROME_NEW_FOLDER_BUTTON_RESID = "com.android.chrome:id/new_folder_btn"
CHROME_NEW_FOLDER_NAME_RESID = "com.android.chrome:id/folder_title"
CHROME_ADD_BOOKMARK_NAVIGATE_UP_DESC = "Navigate up"
CHROME_NEW_FOLDER_NAME_DESC = "Folder name"
CHROME_MOBILE_BOOKMARKS_FOLDER_TXT = "Mobile bookmarks"
CHROME_BOOKMARK_OPTIONS_DESC = "Options"
CHROME_BOOKMARK_OPTIONS_MORE_RESID = "com.android.chrome:id/more"
CHROME_BOOKMARK_OPTIONS_SELECT_TXT = "Select"
CHROME_BOOKMARK_OPTIONS_EDIT_TXT = "Edit"
CHROME_BOOKMARK_OPTIONS_MOVE_TXT = "Move"
CHROME_BOOKMARK_OPTIONS_DELETE_TXT = "Delete"
CHROME_EDIT_BOOKMARK_OPTION_TXT = "Edit bookmark"
CHROME_OPEN_NAVIGATION_DRAWER_DESC = "Open navigation drawer"
CHROME_ADD_ADDRESS_DESC = "Add address"
CHROME_DELETE_BOOKMARK_FOLDER_TXT = "Delete folder"
CHROME_EDIT_BOOKMARK_FOLDER_TXT = "Edit folder"
CHROME_DELETE_BOOKMARK_TXT = "Delete bookmark"
CHROME_EDIT_BOOKMARK_TXT = "Edit bookmark"
CHROME_ADD_TO_HOMESCREEN_TXT = "Add to Home screen"
CHROME_ADD_BUTTON_TXT = "ADD"
CHROME_ADD_TO_HOMESCREEN_TITLE_INPUT_RESID = "com.android.chrome:id/text"
CHROME_INPUT_TEXT_BACKGROUND_COLOR = (17, 34, 170)
CHROME_KEYBOARD_SWITCH_ICON_LOWER_BAR_COLOR = (229, 229, 229)
CHROME_INCOGNITO_TAB_TXT = "incognito"
CHROME_BOOKMARK_LIST_RESID = "com.android.chrome:id/bookmarks_list_view"
CHROME_GOOGLE_SEARCH_TEXTBOX_RESID = "com.android.chrome:id/search_box_text"
CHROME_REPLACE_FILE_TXT = "REPLACE FILE"
CHROME_CREATE_NEW_FILE_TXT = "CREATE NEW FILE"
CHROME_MORE_RESID = "com.android.chrome:id/more"
CHROME_DELETE_TXT = "Delete"
CHROME_INCOGNITO_LEARN_MORE_TXT = "LEARN MORE"
CHROME_TURN_ON_BLUETOOTH = "TURN ON"
CHROME_BOOKMARK_WIDGET_NAME = "Chrome bookmarks"

### Clock
CLOCK_PACKAGE_NAME = "com.google.android.deskclock"
CLOCK_SHORTCUT_NAME = "Clock"
CLOCK_ADD_ALARM_BUTTON_DESC = "Add alarm"
CLOCK_AM_MARKER_TXT = "AM"
CLOCK_PM_MARKER_TXT = "PM"
CLOCK_ALARM_DESC = "Alarm"
CLOCK_EXPAND_ALARM_DESC = "Expand alarm"
CLOCK_DELETE_ALARM_DESC = "Delete alarm"
CLOCK_DISMISS_ALARM_TXT = "DISMISS"
CLOCK_ALARM_TXT = "Alarm"
CLOCK_SNOOZE_ALARM_TXT = "SNOOZE"
CLOCK_SNOOZING_STATUS_TXT = "Snoozing"

### Calendar
CALENDAR_RIGHT_ARROW_RESID = "com.google.android.calendar:id/right_arrow"
CALENDAR_DONE_BUTTON_RESID = "com.google.android.calendar:id/done_button"
CALENDAR_PACKAGE_NAME = "com.google.android.calendar"
CALENDAR_SHORTCUT_NAME = "Calendar"
CALENDAR_ADD_ITEM_RESID = "com.google.android.calendar:id/floating_action_button"
CALENDAR_ADD_EVENT_OPTION_TXT = "Event"
CALENDAR_START_TIME_OPTION_RESID = "com.google.android.calendar:id/start_time"
CALENDAR_END_TIME_OPTION_RESID = "com.google.android.calendar:id/end_time"
CALENDAR_SAVE_EVENT_RESID = "com.google.android.calendar:id/save"
CALENDAR_OK_OPTION_TXT = "OK"
CALENDAR_AM_LABEL_RESID = "android:id/am_label"
CALENDAR_PM_LABEL_RESID = "android:id/pm_label"

### Gmail
GMAIL_SYNC_NOW_RESID = "com.google.android.gm:id/manual_sync"

### Settings
SETTINGS_SHORTCUT_NAME = "Settings"
SETTINGS_PACKAGE_NAME = "com.android.settings"
SETTINGS_WIFI_SWITCH_RESID = "com.android.settings:id/switch_text"
SETTINGS_OPTION_RESID = "com.android.settings:id/title"
SETTINGS_DATA_USAGE_TXT = "Data usage"
SETTINGS_NAVIGATE_UP_DESC = "Navigate up"
SETTINGS_DEVELOPER_OPTIONS_TXT = "Developer options"
SETTINGS_DEBUG_GPU_OVERDRAW_TXT = "Debug GPU overdraw"
SETTINGS_OFF_TXT = "Off"
SETTINGS_ON_TXT = "On"
SETTINGS_SHOW_OVERDRAW_AREAS_OPTION_TXT = "Show overdraw areas"
SETTINGS_SHOW_AREAS_FOR_DEUTERANOMALY_OPTION_TXT = "Show areas for Deuteranomaly"
SETTINGS_LANGUAGE_AND_INPUT_OPTIONS_TXT = "Language & input"
SETTINGS_PINYIN_KEYBOARD_OPTIONS_TXT = "Google Pinyin Input"
SETTINGS_KEYBOARD_SUB_OPTION_TXT = "Keyboard"
SETTINGS_KEYBOARD_THEME_SUB_OPTION_TXT = "Keyboard theme"
SETTINGS_KEYBOARD_THEME_MATERIAL_LIGHT_TXT = "Material Light"
SETTINGS_KEYBOARD_THEME_MATERIAL_DARK_TXT = "Material Dark"
SETTINGS_CURRENT_KEYBOARD_OPTION_TXT = "Current Keyboard"
SETTINGS_CHOOSE_KEYBOARDS_OPTION_TXT = "Choose keyboards"
SETTINGS_TAKE_BUG_REPORT_OPTION_TXT = "Take bug report"
SETTINGS_TAKE_BUG_REPORT_POPUP_REPORT_BUTTON_TXT = "Report"
SETTINGS_TAKE_BUG_REPORT_NOTIFICATION_TXT = "Bug report captured"
SETTINGS_USB_CHOOSER_TXT = "USB"
SETTINGS_USB_CHOOSER_MTP_OPTION_TXT = "File transfer"
SETTINGS_USB_CHOOSER_PTP_OPTION_TXT = "PTP"
SETTINGS_ACCOUNTS_OPTION_TXT = "Accounts"
SETTINGS_GOOGLE_ACCOUNT_OPTION_TXT = "Google"
SETTINGS_GOOGLE_ACCOUNT_REMOVE_TXT = "Remove account"
SETTINGS_GOOGLE_ACCOUNT_REMOVE_POPUP_TXT = "REMOVE ACCOUNT"
SETTINGS_LOCATION_OPTION_TXT = "Location"
SETTINGS_LOCATION_MODE_TXT = "Mode"
SETTINGS_LOCATION_HIGH_ACCURACY_TXT = "High accuracy"
SETTINGS_SHOW_GPU_VIEW_UPDATES_TXT = "Show GPU view updates"
SETTINGS_SECURITY_TXT = "Security"
SETTINGS_SCREEN_LOCK_TXT = "Screen lock"
SETTINGS_SCREEN_LOCK_PIN_TXT = "PIN"
SETTINGS_SCREEN_LOCK_SWIPE_TXT = "Swipe"
SETTINGS_STORAGE_AND_USB_OPTIONS_TXT = "Storage"
SETTINGS_SECURE_STARTUP_DECLINE_TXT = "No thanks"
SETTINGS_SECURE_STARTUP_DECLINE_CONTINUE_TXT = "Continue"
SETTINGS_ENABLE_PIN_NOTIFICATIONS_TXT = "Show all notification content"
SETTINGS_ENABLE_PIN_DONE_TXT = "Done"
SETTINGS_REMOVE_DEVICE_PROTECTION_TXT = "Yes, remove"
SETTINGS_SMART_LOCK_TXT = "Smart Lock"
SETTINGS_SMART_LOCK_TRUSTED_PLACES_TXT = "Trusted places"
SETTINGS_SMART_LOCK_ADD_TRUSTED_PLACE_TXT = "Add trusted place"
SETTINGS_SMART_LOCK_SELECT_CURRENT_LOCATION_TXT = "Select this location"
SETTINGS_TRUSTED_PLACE_NAME_RESID = "com.google.android.gms:id/trusted_place_name"
SETTINGS_TRUSTED_PLACES_SEARCH_RESID = "com.google.android.gms:id/places_ui_menu_main_search"
SETTINGS_TRUSTED_PLACE_INFO_RESID = "com.google.android.gms:id/info"
SETTINGS_TRUSTED_PLACE_DELETE_TXT = "Delete"
SETTINGS_TRUSTED_FIRST_TIME_RESID = "com.google.android.gms:id/auth_trust_agent_first_use_notification_button_id"
SETTINGS_TRUSTED_PLACE_SUGGESTION_PRIMARY_RESID = "com.google.android.gms:id/place_autocomplete_prediction_primary_text"
SETTINGS_MORE_TXT = "More"
SETTINGS_MOBILE_NETWORKS_TXT = "Cellular networks"
SETTINGS_NETWORK_TYPE_TXT = "Preferred network type"
SETTINGS_ACCESS_POINT_TXT = "Access Point Names"
SETTINGS_NEW_APN_TXT = "New APN"
SETTINGS_NEW_APN_NAME_TXT = "Name"
SETTINGS_NEW_APN_APN_TXT = "APN"
SETTINGS_APN_RADIO_BUTTON_RESID = "com.android.settings:id/apn_radiobutton"
SETTINGS_MORE_OPTIONS_TXT = "More options"
SETTINGS_SAVE_TXT = "Save"
SETTINGS_RESET_DEFAULT_TXT = "Reset to default"
SETTINGS_AIRPLANE_MODE_TXT = "Airplane mode"
SETTINGS_3G_TXT = "3G"

### GMail
GMAIL_APP_NAME = "Gmail"
GMAIL_TAKE_BUG_REPORT_ATTACHEMENT_PREFIX_TXT = "bugreport"
GMAIL_TAKE_BUG_REPORT_ATTACHEMENT_SUBTITLE_RESID = "com.google.android.gm:id/attachment_tile_subtitle"
GMAIL_PACKAGE_NAME = "com.google.android.gm"

### Notifications
NOTIFICATIONS_MAIN_COLUMN_RESID = "android:id/notification_main_column"
NOTIFICATIONS_CLEAR_ALL_RESID = "com.android.systemui:id/dismiss_text"
NOTIFICATIONS_NOTIFICATION_TITLE_RESID = "android:id/title"
NOTIFICATIONS_USE_DEVICE_LOCATION_TXT = "wants to use your device's location"
NOTIFICATIONS_ALLOW_LOCATION_TXT = "Allow"
NOTIFICATIONS_BLOCK_LOCATION_TXT = "Block"
NOTIFICATIONS_NOTIFICATION_TEXT_RESID = "android:id/text"
NOTIFICATIONS_AIRPLANE_ON_DESC = "Airplane mode on."
NOTIFICATIONS_AIRPLANE_OFF_DESC = "Airplane mode off."
NOTIFICATIONS_BATTERY_RESID = "com.android.systemui:id/battery"

### Misc UI Elements
APPS_BUTTON_DESC = "Apps"
DISMISS_TASK_RESID = "com.android.systemui:id/dismiss_task"
TITLE_ELEMENT_RESID = "android:id/title"
SUMMARY_ELEMENT_RESID = "android:id/summary"
UI_TRUE = "true"
UI_FALSE = "false"
LAUNCHER_WORKSPACE_SCROLL_TYPE = "horizontal"
CLEAR_ALL_RUNNING_APPS_TXT = "CLEAR ALL"

### Widgets
WIDGET_LAUNCHER_BUTTON_RESID = "com.google.android.googlequicksearchbox:id/widget_button"
WIDGET_LIST_SCROLL_TYPE = "horizontal"
WIDGETS_MENU_TXT = "WIDGETS"

### Android Misc
ANDROID_WORKSPACE_RESID = "com.google.android.googlequicksearchbox:id/workspace"
ANDROID_WIDGET_BUTTON = "android.widget.Button"
ANDROID_VIEW_CLASSNAME = "android.view.View"
ANDROID_WIDGET_TEXT_VIEW = "android.widget.TextView"
ANDROID_WIDGET_IMAGE = "android.widget.Image"
ANDROID_WIDGET_IMAGE_BUTTON = "android.widget.ImageButton"
ANDROID_WIDGET_HORIZONTAL_SCROLL_VIEW = "android.widget.HorizontalScrollView"
ANDROID_WIDGET_LINEAR_LAYOUT = "android.widget.LinearLayout"
ANDROID_KEYGUARD_ENTER_RESID = "com.android.systemui:id/key_enter"
ANDROID_KEYGUARD_PIN_VIEW_RESID = "com.android.systemui:id/keyguard_pin_view"
ANDROID_WIDGET_EDIT_TEXT = "android.widget.EditText"
ANDROID_WIDGET_ALERT_TITLE = "android:id/alertTitle"
ANDROID_WIDGET_LIST_VIEW = "android.widget.ListView"
ANDROID_WIDGET_LIST_RESID = "android:id/list"
ANDROID_WIDGET_TITLE_RESID = "android:id/title"
ANDROID_CHECKBOX_CLASSNAME = "android.widget.CheckBox"
ANDROID_WIDGET_SWITCH_CLASSNAME = "android.widget.Switch"
ANDROID_FRAME_LAYOUT = "android.widget.FrameLayout"
ANDROID_MESSAGE_RESID = "android:id/message"

### OS
OS_OPEN_JUST_ONCE_TXT = "Just once"
APP_CRASH_POPUP_BEGIN_TXT = "Unfortunately"
APP_CRASH_POPUP_END_TXT = "has stopped"

### Youtube
YOUTUBE_PACKAGE_NAME = "com.google.android.youtube"

### Internet Misc
W3SCHOOLS_START_WEB_WORKER = "Start Worker"
W3SCHOOLS_STOP_WEB_WORKER = "Stop Worker"
W3SCHOOLS_WEB_WORKER_COUNT_NUMBERS = "Count numbers:"

### Launcher stuff
LAUNCHER_PACKAGE_NAME = "com.android.launcher"
LAUNCHER_SCROLL = "vertical"

### Popups
POPUP_OK = "OK"
POPUP_SKIP = "SKIP"

### Add Account
ADD_ACCOUNT_EMAIL_DESC = "Enter your email"
ADD_ACCOUNT_PASS_RESID = "password"
ADD_ACCOUNT_NEXT_DESC = "NEXT"
ADD_ACCOUNT_ACCEPT_DESC = "ACCEPT"
ADD_ACCOUNT_AGREE_BACKUP_RESID = "com.google.android.gms:id/agree_backup"


### GMS Apps
GMS_CAMERA_PACKAGE = "com.google.android.GoogleCamera"
GMS_GOOGLE_PLUS_PACKAGE = "com.google.android.apps.plus"
GMS_HANGOUTS_PACKAGE = "com.google.android.talk"
GMS_PHOTOS_PACKAGE = "com.google.android.apps.plus"
GMS_VOICE_SEARCH_PACKAGE = "com.google.android.googlequicksearchbox"

### Keyboard
GOOGLE_KEYBOARD_NAME = "Google Keyboard"
PINYIN_KEYBOARD_NAME = "Chinese Pinyin"
JAPANESE_KEYBOARD_NAME = "Japanese"

### Camera
CAMERA_PACKAGE = "com.android.camera2"
CAMERA_SHORTCUT_NAME = "Camera"
CAMERA_LAUNCH_CONFIRM_BUTTON_RESID = "com.android.camera2:id/confirm_button"
CAMERA_LAUNCH_CONFIRM_TXT_SEQ = ["NEXT"]
CAMERA_SHUTTER_RESID = "com.android.camera2:id/shutter_button"
LEFT_SWIPE_MENU_CAMERA_TXT = "Camera"
LEFT_SWIPE_MENU_VIDEO_TXT = "Video"
CAMERA_OPTIONS_DESC = "More options"
CAMERA_DETAILS_TXT = "Details"
CAMERA_MEDIA_DETAIL_RESID = "android:id/text1"
CAMERA_TOGGLE_BUTTON_RESID = "com.android.camera2:id/camera_toggle_button"
CAMERA_BACK_DESC = "Back camera"
CAMERA_FRONT_DESC = "Front camera"
CAMERA_MODE_OPTIONS_RESID = "com.android.camera2:id/mode_options_toggle"
CAMERA_MODE_OPTIONS_OVERLAY_RESID = "com.android.camera2:id/mode_options_overlay"
CAMERA_SETTINGS_RESID = "com.android.camera2:id/settings_button"
CAMERA_RES_QUALITY_MENU_TXT = "Resolution & quality"
CAMERA_FRONT_VID_OPTS_TXT = "Front camera video"
CAMERA_BACK_VID_OPTS_TXT = "Back camera video"
CAMERA_FRONT_IMG_OPTS_TXT = "Front camera photo"
CAMERA_BACK_IMG_OPTS_TXT = "Back camera photo"
CAMERA_CONFIG_OPTIONS_RESID = "android:id/text1"
CAMERA_MANUAL_EXPOSURE_DESC = "Manual Exposure Compensation"
CAMERA_ADVANCED_OPTIONS_TXT = "Advanced"
CAMERA_MANUAL_EXPOSURE_OPTIONS_TXT = "Manual exposure"
CAMERA_EXPOSURE_COMPENSATION_RESIDS = ["com.android.camera2:id/exposure_p2",
                                       "com.android.camera2:id/exposure_p1",
                                       "com.android.camera2:id/exposure_n1",
                                       "com.android.camera2:id/exposure_n2",
                                       "com.android.camera2:id/exposure_0"]
CAMERA_ALLOW_LOCATION_ACCESS_TXT = "Allow"

### Photos
PHOTOS_SHORTCUT_NAME = "Photos"
PHOTOS_PACKAGE_NAME = "com.google.android.apps.photos"
PHOTOS_SIGN_IN_ALTERNATIVES_TXT = ["Sign In", "Sign in"]
PHOTOS_GET_STARTED_BUTTON_RESID = "com.google.android.apps.photos:id/get_started"
PHOTOS_CONTINUE_BUTTON_RESID = "com.google.android.apps.photos:id/continue_button"
PHOTOS_NEXT_BUTTON_RESID = "com.google.android.apps.photos:id/next_button"
PHOTOS_SEARCH_BUTTON_RESID = "com.google.android.apps.photos:id/fab"
PHOTOS_APPLY_BUTTON_RESID = "com.google.android.apps.photos:id/apply_button"
PHOTOS_CANCEL_BUTTON_RESID = "com.google.android.apps.photos:id/cancel_button"
PHOTOS_PHOTO_TILE_RESID = "com.google.android.apps.photos:id/list_photo_tile_view"
PHOTOS_CROP_BUTTON_RESID = "com.google.android.apps.photos:id/cpe_crop_tool"
PHOTOS_FILTER_BUTTON_RESID = "com.google.android.apps.photos:id/cpe_looks_tool"
PHOTOS_FILTER_OPTIONS_DESC = ["filter None", "filter Mars", "filter Phobos", "filter Deimos", "filter Ceres",
                              "filter Juno", "filter Saturn", "filter Mimas", "filter Rhea", "filter Dione",
                              "filter Ariel", "filter Triton", "filter Venus", "filter Pluto", "filter Eris"]
PHOTOS_FILTER_SCROLLER_RESID = "com.google.android.apps.photos:id/cpe_looks_list_scroll_view"
PHOTOS_CROP_OVERLAY_RESID = "com.google.android.apps.photos:id/cpe_crop_overlay"
PHOTOS_DONE_BUTTON_TXT = "Done"
PHOTOS_PHOTO_DETAILS_OPTION_RESID = "com.google.android.apps.photos:id/details"
PHOTOS_PHOTO_EDIT_OPTION_RESID = "com.google.android.apps.photos:id/edit"
PHOTOS_PHOTO_SHARE_OPTION_RESID = "com.google.android.apps.photos:id/share"
PHOTOS_PHOTO_TRASH_OPTION_RESID = "com.google.android.apps.photos:id/trash"
PHOTOS_DELETE_RESID = "com.google.android.apps.photos:id/delete"
PHOTOS_PHOTO_DESC = "Photo"
PHOTOS_VIDEO_DESC = "Video"
PHOTOS_DETAIL_LABEL_RESID = "com.google.android.apps.photos:id/label"
PHOTOS_DETAIL_VALUE_RESID = "com.google.android.apps.photos:id/value"
PHOTOS_ACCEPT_CHANGES_RESID = "com.google.android.apps.photos:id/cpe_strength_accept"
PHOTOS_CANCEL_CHANGES_RESID = "com.google.android.apps.photos:id/cpe_strength_cancel"
PHOTOS_SAVE_CHANGES_RESID = "com.google.android.apps.photos:id/cpe_save_button"
PHOTOS_ROTATE_BUTTON_RESID = "com.google.android.apps.photos:id/cpe_rotate_90"
PHOTOS_CROP_AND_ROTATE_RESET_RESID = "com.google.android.apps.photos:id/cpe_crop_and_rotate_reset"
PHOTOS_MOVE_TO_TRASH_RESID = "com.google.android.apps.photos:id/move_to_trash"
PHOTOS_SEARCH_BOX_RESID = "com.google.android.apps.photos:id/search_box"
PHOTOS_SEARCH_CATEGORY_PLACES_TXT = "Places"
PHOTOS_SEARCH_CATEGORY_TYPES_TXT = "Types"
PHOTOS_ADJUSTMENT_SEEK_BAR_RESID = "com.google.android.apps.photos:id/cpe_strength_seek_bar"
PHOTOS_ADJUSTMENT_AUTO_RESID = "com.google.android.apps.photos:id/cpe_adjustments_reset"
PHOTOS_ADJUSTMENT_LIGHT_RESID = "com.google.android.apps.photos:id/cpe_adjustments_light"
PHOTOS_ADJUSTMENT_COLOR_RESID = "com.google.android.apps.photos:id/cpe_adjustments_color"
PHOTOS_ADJUSTMENT_POP_RESID = "com.google.android.apps.photos:id/cpe_adjustments_pop"
PHOTOS_ADJUSTMENT_VIGNETTE_RESID = "com.google.android.apps.photos:id/cpe_adjustments_vignette"
PHOTOS_PHOTO_MORE_OPTIONS_RESID = "com.google.android.apps.photos:id/actionbar_overflow"
PHOTOS_PHOTO_USE_AS_OPTION_TXT = "Use as"
PHOTOS_PHOTO_USE_AS_WALLPAPER_OPTION_TXT = "Wallpaper"
PHOTOS_PHOTO_USE_AS_CONTACT_PHOTO_OPTION_TXT = "Contact photo"
PHOTOS_SET_WALLPAPER_BUTTON_RESID = "com.google.android.googlequicksearchbox:id/set_wallpaper_button"
PHOTOS_BLUE_WALLPAPER_COLOR = (20, 50, 100)
PHOTOS_PHOTO_VIEW_RESID = "com.google.android.apps.photos:id/photo_view"
PHOTOS_PHOTO_PREVIEW_RESID = "com.google.android.apps.photos:id/cpe_image_preview"
PHOTOS_DISCARD_CHANGES_BUTTON_TXT = "DISCARD"
PHOTOS_PHOTO_SHARE_BUTTON_RESID = "com.google.android.apps.photos:id/share_button"
PHOTOS_SHARE_LINK_ALTERNATIVES_TXT = ["Get link", "Create link"]
PHOTOS_SHOW_NAV_DRAWER_DESC = "Show Navigation Drawer"
PHOTOS_SHARED_LINKS_TXT = "Shared links"
PHOTOS_SHARED_ALBUMS_TXT = "Shared albums"
PHOTOS_DEVICE_FOLDERS_TXT = "Device folders"
PHOTOS_SHARED_LINK_MENU_RESID = "com.google.android.apps.photos:id/overflow"
PHOTOS_DELETE_SHARED_LINK_OPTION_TXT = "Delete link"
PHOTOS_DELETE_SHARED_LINK_CONFIRMATION_TXT = "Delete link"
PHOTOS_DELETE_DEVICE_COPY_TXT = "Delete device copy"
PHOTOS_DELETE_DEVICE_COPY_CONFIRM_TXT = "Delete"
PHOTOS_VIDEO_CONTENT_DESC = "Video"
PHOTOS_PHOTO_CONTENT_DESC = "Photo"
PHOTOS_TRASH_OPTION_TXT = "Trash"
PHOTOS_EMPTY_TRASH_OPTION_TXT = "Empty trash"
PHOTOS_EMPTY_TRASH_CONFIRMATION_TXT = "Delete"
PHOTOS_DELETE_SHARED_ITEMS_TXT = "Remove"
PHOTOS_MOVE_TO_TRASH_TXT = "Move to trash"
PHOTOS_AUTO_BACKUP_TOGGLE_OPTION_RESID = "com.google.android.apps.photos:id/autobackup_folder_toggle_icon"
PHOTOS_AUTO_BACKUP_TOGGLE_ON_DESC = "Turn on backup"

### Contacts
CONTACTS_SHORTCUT_NAME = "Contacts"
CONTACTS_PACKAGE_NAME = "com.android.contacts"
CONTACTS_CONTACT_LIST_ENTRY_RESID = "com.android.contacts:id/cliv_name_textview"
CONTACTS_MENU_SEARCH_RESID = "com.android.contacts:id/menu_search"
CONTACTS_SEARCH_VIEW_RESID = "com.android.contacts:id/search_view"
CONTACTS_SEARCH_VIEW_TXT = "Find contacts"
CONTACTS_AAA_SEARCH_TXT = "aaa"
CONTACTS_ADD_CONTACT_BUTTON_RESID = "com.android.contacts:id/floating_action_button"
CONTACTS_OK_TXT = "OK"
CONTACTS_DELETE_TXT = "Delete"
CONTACTS_FAVORITES_TXT = "Favorites"
CONTACTS_ALL_CONTACTS_TXT = "All contacts"
CONTACTS_NO_CONTACTS_TXT = "No contacts."
CONTACTS_MORE_OPTIONS_TXT = "More options"
CONTACTS_IMPORT_EXPORT_TXT = "Import/export"
CONTACTS_IMPORT_EXPORT_TITLE_TXT = "Import/export contacts"
CONTACTS_IMPORT_CONTACTS_BTN_RESID = "com.android.contacts:id/import_contacts_button"
CONTACTS_IMPORT_FROM_SIM_TXT = "Import from SIM card"

### Import from sim
IMPORT_FROM_SIM_PACKAGE_NAME = "com.android.phone"
IMPORT_FROM_SIM_TITLE_TXT = "Select contacts to import"
IMPORT_FROM_SIM_CONTACT_RESID = "android:id/text1"
IMPORT_FROM_SIM_IMPORT_TXT = "Import"
IMPORT_FORM_SIM_ALL_TXT = "Import all"

### Add Account
ADD_ACCOUNT_PACKAGE_NAME = "com.google.android.gms"

### Action Menu
ACTION_MENU_COPY_RESID = "com.android.chrome:id/select_action_menu_copy"
ACTION_MENU_SELECT_ALL_RESID = "com.android.chrome:id/select_action_menu_select_all"
ACTION_MENU_BAR_RESID = "com.android.chrome:id/action_mode_bar"

### Api Tests
API_TESTS_EDIT_RESID = "com.intel.test.apitests:id/edit_text"

### Downloads
DOWNLOADS_SHORTCUT_NAME = "Downloads"
DOWNLOADS_PACKAGE_NAME = "com.android.documentsui"
DOWNLOADS_FRAME_LAYOUT_CLASS = "android.widget.FrameLayout"
DOWNLOADS_FILE_TITLE_RESID = "android:id/title"
DOWNLOADS_FILE_SIZE_RESID = "com.android.documentsui:id/size"
DOWNLOADS_FILE_SUMMARY_RESID = "android:id/summary"
DOWNLOADS_FILE_DATE_RESID = "com.android.documentsui:id/date"
DOWNLOADS_SORT_OPTION_DESC = "Sort by"
DOWNLOADS_SORT_OPTION_NAME_TXT = "By name"
DOWNLOADS_SORT_OPTION_DATE_TXT = "By date modified"
DOWNLOADS_SORT_OPTION_SIZE_TXT = "By size"
DOWNLOADS_LIST_VIEW_DESC = "List view"
DOWNLOADS_GRID_VIEW_DESC = "Grid view"
DOWNLOADS_MORE_OPTIONS_DESC = "More options"
DOWNLOADS_ROOTS_LIST_RESID = "com.android.documentsui:id/roots_list"
DOWNLOADS_SHOW_ROOTS_DESC = "Show roots"
DOWNLOADS_SHOW_FILE_SIZE_TXT = "Show file size"
DOWNLOADS_VIEW_TXT = "Downloads"
DOWNLOADS_RETRY_TXT = "RETRY"


### Status bar
STATUS_BAR_DISMISS_RESID = "com.android.systemui:id/dismiss_text"
STATUS_BAR_PACKAGE = "com.android.systemui"

### Colors and related constants

DELETE_BAR_COLOR = (250, 250, 250)
DELETE_BAR_BOTTOM_COLOR = (0, 150, 136)
DELETE_BAR_ITEMS_COLOR = (32, 32, 32)
COLOR_WHITE = (255, 255, 255)
DELETE_BUTTON_DIRECTION = (-3, 2)
# the color of the 3 android buttons situated on the bottom menu bar
COLOR_ANDROID_BUTTONS_GREY = (221, 221, 221)

### System OS various strings

SYSTEM_OS_IMMERSIVE_APP_SHORTCUT_NAME = "Immersive UI"
SYSTEM_OS_ENTER_IMMERSIVE_MODE_TXT = "Enter Immersive Mode"
SYSTEM_OS_EXIT_IMMERSIVE_MODE_TXT = "Exit Immersive Mode"

### Storage USB related strings

STORAGE_USB_FORMAT_TXT = "Format"
STORAGE_USB_ERASE_AND_FORMAT_TXT = "ERASE & FORMAT"
STORAGE_USB_DONE_TXT = "DONE"
STORAGE_USB_FORMAT_AS_INTERNAL_TXT = "Format as internal"
STORAGE_USB_MOVE_LATER_TXT = "Move later"
STORAGE_USB_MOVE_TXT = "MOVE"
STORAGE_USB_OK_TXT = "OK"
STORAGE_USB_NEXT_TXT = "NEXT"
STORAGE_USB_MOVE_NOW_TXT = "Move now"
STORAGE_FULL_STORAGE_NOTIFICATION_COLOR = (244, 81, 30)
STORAGE_SDCARD_TXT = "SD card"
STORAGE_SDCARD_UNOUNT_ICON_RESID = "com.android.settings:id/unmount"
STORAGE_EJECTED_TXT = "Ejected"
STORAGE_UNMOUNT_TXT = "Eject"
STORAGE_SDCARD_MOUNT_TXT = "Mount"
STORAGE_UNMOUNT_RESID = "com.android.settings:id/confirm"

### Android Permissions

PERMISSION_WRITE_EXTERNAL_STORAGE = "android.permission.WRITE_EXTERNAL_STORAGE"

### MESSAGING
MESSAGING_SHORTCUT_NAME = "Messenger"
MESSAGING_START_CONVERSATION = "com.google.android.apps.messaging:id/start_new_conversation_button"
MESSAGING_RECEIPIENT = "com.google.android.apps.messaging:id/recipient_text_view"
MESSAGING_MESSAGE_BOX = "com.google.android.apps.messaging:id/compose_message_text"
MESSAGING_SEND = "com.google.android.apps.messaging:id/send_message_button"
MESSAGING_MORE_OPTIONS_TXT = "More options"
MESSAGING_SETTINGS = "com.google.android.apps.messaging:id/title"
MESSAGING_DELIVERY_TXT = "SMS delivery reports"
MESSAGING_SENDERS_LIST = "com.google.android.apps.messaging:id/swipeableContent"
MESSAGING_CHAR_COUNTER = "com.google.android.apps.messaging:id/char_counter"
MESSAGING_ADD_CONTACT_TXT = "Add contact"
MESSAGING_ADD_CONTACT_UPPER_TXT = "Add Contact"
MESSAGING_CREATE_NEW_CONTACT_TXT = "Create new contact"
MESSAGING_CONTACT_NAME_TXT = "Name"
MESSAGING_CONTACT_SAVE_TXT = "com.android.contacts:id/menu_save"
MESSAGING_CONTACT_NAME = "com.google.android.apps.messaging:id/contact_name"
MESSAGING_CONTACT_ICON = "com.google.android.apps.messaging:id/contact_icon"
MESSAGING_DELETE_TXT = "Delete"
MESSAGING_CONFIRMATION_TXT = "OK"
MESSAGING_ALL_CONTACTS_TXT = "All contacts"
MESSAGING_ADVANCED_TXT = "Advanced"
MESSAGING_SETTINGS_TXT = "Settings"
MESSAGING_KEEP_LOCAL_TXT = "Keep local"
MESSAGING_TEXT = "com.google.android.apps.messaging:id/message_text"
MESSAGING_SWIPEABLE_CONTENT = "com.google.android.apps.messaging:id/swipeableContent"
MESSAGING_TEXT_AND_INFO = "com.google.android.apps.messaging:id/message_text_and_info"
MESSAGING_PACKAGE = "com.google.android.apps.messaging"
MESSAGING_FORWARD_TXT = "Forward"
MESSAGING_SEND_MESSAGE_TXT = "Send message"
MESSAGING_CONFIRM_PARTICIPANTS = "com.google.android.apps.messaging:id/action_confirm_participants"

# DIALER
DIALER_SHORTCUT_NAME = "Phone"
DIALER_SEARCH_VIEW = "com.android.dialer:id/search_view"
DIALER_CONFIRMATION = "OK"
DIALER_END_CALL = "com.android.dialer:id/floating_end_call_action_button"
DIALER_TELEPHONE_SEARCH_TXT = "Search contacts & places"
DIALER_PHONE_SEARCH_TXT = "Enter a name or phone number"
DIALER_MISSED_CALL_TXT = "Missed call"
DIALER_INCOMING_CALL_TXT = "Incoming call"
DIALER_DISMISS_TXT = "Dismiss"
DIALER_KEYBOARD = "com.android.dialer:id/floating_action_button"
DIALER_CALL = "com.android.dialer:id/dialpad_floating_action_button"
DIALER_DIGITS_INPUT = "com.android.dialer:id/digits"
DIALER_MMI_POPUP = "android:id/message"
DIALER_MORE_OPTIONS_TXT = "More options"
DIALER_SETTINGS_TXT = "Settings"
DIALER_CALLS_TXT = "Calls"
DIALER_CALL_TXT = "Call"
DIALER_CALL_WAITING_TXT = "Call waiting"
DIALER_ADDITIONAL_SETTINGS_TXT = "Additional settings"
DIALER_OPTIONS = "com.android.dialer:id/dialtacts_options_menu_button"
DIALER_CALLER_ID = "Caller ID"
DIALER_SUMMARY = "android:id/summary"
DIALER_VOICEMAIL_TXT = "Voicemail"
DIALER_SETUP_TXT = "Setup"
DIALER_VOICEMAIL_EDITBOX = "android:id/edit"
DIALER_RECENTS = "Recents"
DIALER_CONTACTS = "Contacts"
DIALER_CALL_DETAILS = "com.android.dialer:id/details_action"
DIALER_PRIMARY_ACTION_BUTTON = "com.android.dialer:id/primary_action_button"
DIALER_CALLER_NUMBER = "com.android.dialer:id/caller_number"
DIALER_CALLER_NAME = "com.android.dialer:id/caller_name"
DIALER_CALL_BACK = "com.android.dialer:id/call_back_button"
DIALER_RELATIVE_LAYOUT = "android.widget.RelativeLayout"
DIALER_SPEED_DIAL = "Speed dial"
DIALER_CONTACT_NAME = "com.android.dialer:id/name"
DIALER_GLOW_PAD_VIEW_RESID = "com.android.dialer:id/glow_pad_view"
DIALER_MISSED_CALL_TXT = "Missed call"
DIALER_HANG_UP_TXT = "Hang up"
DIALER_ANSWER_TXT = "Answer"
DIALER_CALL_FORWARDING = "Call forwarding"
DIALER_ALWAYS_FORWARD_TXT = "Always forward"
DIALER_EDIT = "android:id/edit"
DIALER_TURN_ON_TXT = "Turn on"
DIALER_TURN_OFF_TXT = "Turn off"
DIALER_WHEN_UNREACHABLE_TXT = "When unreachable"
DIALER_WHEN_UNANSWERED_TXT = "When unanswered"
DIALER_HOLD_CALL_DESC = "Hold Call"
DIALER_RESUME_CALL_DESC = "Resume Call"
DIALER_ON_HOLD_TXT = "On hold"
DIALER_CALL_INFO_RESID = "com.android.dialer:id/primary_call_info_container"
DIALER_FDN_SETTINGS_TXT = "Fixed Dialing Numbers"
DIALER_ENABLE_FDN_TXT = "Enable FDN"
DIALER_DISABLE_FDN_TXT = "Disable FDN"
DIALER_CHANGE_PIN_2_TXT = "Change PIN2"
DIALER_ENTER_PUK_2_TXT = "Enter PUK2 code"
DIALER_OLD_PIN_2_TXT = "Old PIN2"
DIALER_PIN_CHANGE_TXT = "PIN change"
DIALER_SECONDARY_RESID = "com.android.dialer:id/secondaryCallName"

USSD_SEND_TXT = "Send"
USSD_CANCEL_TXT = "Cancel"
USSD_OK_TXT = "OK"
USSD_INPUT_RESID = "com.android.phone:id/input_field"

COMPLETE_ACTION_USING = "Complete action using"
COMPLETE_ACTION_ONCE = "Just once"
COMPLETE_ACTION_ALWAYS = "Always"
