#!/system/bin/sh
# $Id: stopmm,v 1.3 2005/10/20 15:54:42 tfcreela Exp $

echo "Stopping Matrix Multiply Test..."

ps -e | grep "\<runmm"

Pid=`ps -e | grep "runmm" | awk '{print $1}'`

for i in $Pid
do
    echo "kill -9 $i"
    kill -9 $i
    echo "process $i was killed"
done

echo "Stop Matrix Multiply Test At:"
$(date)
